### ISSUE TITLE
issue while accessing HANA DB

### ISSUE THREAD

**Issue by NagarajG05** [lgaa/HANAschemaspy#2]
Hi,

Thanks for such a useful tool. 

Could you please help me to resolve the below issue, I am trying to connect to HANA DB

I have placed hana.properties file under path _schemaspy-6.1.0\BOOT-INF\classes\org\schemaspy\types_

![image](https://user-images.githubusercontent.com/66556504/142738762-dc68d961-4db7-4184-bc04-42b83b7efe33.png)

**Comment by lgaa** [comment]
Didn't give me error with schemaspy-6.1.0 and [ngdbc](https://mvnrepository.com/artifact/com.sap.cloud.db.jdbc/ngdbc) 2.4.63  and another test with 2.9.8.
Sorry don't have a HANA instance available to test.
![image](https://user-images.githubusercontent.com/11938275/143328850-23327c5e-0c88-4fc4-a1b2-33581c889def.png)
the jar is not modified other than the hana.properties adding and it is properly handled with a compression utility?

**Comment by NagarajG05** [comment]
Thanks for your response. 
Below are the steps I followed to add properties for HANA.

Opened the zipped(compressed) _schemaspy-6.1.0 2_ folder and placed the _hana.properties_ file (as shown in the below screenshot) and saved zipped folder 

![image](https://user-images.githubusercontent.com/66556504/144139335-c934c11d-f520-4ac6-be10-dde67517d0c6.png)


then below is the command I tried to execute, still facing same issue.
_java.exe -jar C:\Users\user\Videos\schemaspy-6.1.0.jar -t hana -dp C:\Users\user\Videos\ngdbc-2.9.8.jar    -host host_name  -port 30041  -u user  -o C:\Temp  -gv C:\Program Files (x86)\Graphviz\bin\dot.exe -vizjs_

**Comment by NagarajG05** [comment]
the issue is resolved after commenting extend 

![image](https://user-images.githubusercontent.com/66556504/144287125-c4cad935-c0f8-47ae-89bf-9f029eda9172.png)
